### PR TITLE
refactor storage pod handling

### PR DESCRIPTION
**Pull request by timogoebel**
Just a little refactoring for vm cloning to also check whether storage_pod is nil and not just if the key exists

### CODE REVIEW

**Comment by jrgarcia** [comment]
:+1:

**Comment by iNecas** [comment]
Without this patch, the `vm_clone` is broken as the original call for `get_storage_pod` has different number of arguments.  (see http://projects.theforeman.org/issues/14051). Would you mind releasing 0.6.1 with this, as it pretty limits the usage.

**Comment by jrgarcia** [comment]
@iNecas Releasing now.

**Comment by iNecas** [comment]
Thanks @jrgarcia !

**Pull request merged**
