### PR TITLE
support updating of server cpus and memory

### PR DESCRIPTION
**Pull request by timogoebel**
This PR implements updating of cpus, corespersocket and memory for an existing vm.

### CODE REVIEW

**Comment by timogoebel** [comment]
@jrgarcia : Would you mind releasing a new version with these changes if you find the time so we can use them in Foreman? Thanks a lot.

**Comment by jrgarcia** [comment]
@timogoebel No problem! Sorry, I'm on vacation and only had my phone available when I merged it.

**Comment by timogoebel** [comment]
> Sorry, I'm on vacation and only had my phone available when I merged it.

I thought so, no rush. Enjoy your vacation and the rest of 2016.

**Comment by jrgarcia** [comment]
1.6.0 is now available: https://rubygems.org/gems/fog-vsphere/versions/1.6.0

**Comment by timogoebel** [comment]
Thank you, @jrgarcia.

**Pull request merged**
