### PR TITLE
fetch datacenter by vm_mob_ref.path if user does not have permission to access hosts

### PR DESCRIPTION
**Pull request by manchiu**

### CODE REVIEW

**Comment by chris1984** [comment]
@manchiu thanks for the pr, can you rebase the commit to 1, it looks like it has some extra stuff in it? Once that is done I will kick off the tests and merge if they pass.

**Comment by manchiu** [comment]
@chris1984 Rebased

**Comment by chris1984** [comment]
Thanks starting to test this, sorry for the delay it was a holiday here in the US

**Comment by manchiu** [comment]
> Thanks starting to test this, sorry for the delay it was a holiday here in the US

That's ok. Thanks @chris1984

**Pull request merged**
