### PR TITLE
add cluster storage and network filter

### PR DESCRIPTION
**Pull request by timogoebel**
This PR adds the ability to view datastores and networks filtered by cluster.

### CODE REVIEW

**Comment by jrgarcia** [comment]
@timogoebel The code looks fine, but is there any chance you can add tests? If not, let me know, and I'll go ahead and merge it and give the testing a shot.

**Comment by angystardust** [comment]
@timogoebel , can you also try to implement filtering on the storage_pod obects?

**Comment by timogoebel** [comment]
@jrgarcia : I added basic test coverage. What do you think?
@angystardust : Filtering on the storage pod objects is a lot more difficult. I prefer adding this later in a separate PR.

**Comment by jrgarcia** [comment]
@timogoebel Thanks! Today is a national holiday for me. I'll look at getting this merged in tomorrow.

**Comment by timogoebel** [comment]
@jrgarcia : Thanks, enjoy the rest of your Memorial Day weekend...

**Comment by jrgarcia** [comment]
@timogoebel Thanks again for your contributions!

**Pull request merged**
