### PR TITLE
Check datastore for existence prior vm_clone

### PR DESCRIPTION
**Pull request by ezr-ondrej**

### CODE REVIEW

**Comment by chris1984** [comment]
@ezr-ondrej im fine with merging and ignoring the codeclimate refactor warnings. Do you want me to make a release after this?

**Comment by ezr-ondrej** [comment]
Yeah, we are past point of return with codeclimate xD
I guess minor release wouldn't hurt unless you've got something :thinking: 
Or if you wouldn't mind to wait till friday, I'd like to try finish up #196

**Comment by chris1984** [comment]
> Yeah, we are past point of return with codeclimate xD
> I guess minor release wouldn't hurt unless you've got something 🤔
> Or if you wouldn't mind to wait till friday, I'd like to try finish up #196

I'm fine with waiting

**Comment by ezr-ondrej** [comment]
This one should be ready to get in though, right?

**Comment by chris1984** [comment]
@ezr-ondrej yeah this one is good to go

**Pull request merged**
