### PR TITLE
Add vm_update class for improved vm reconfiguration

### PR DESCRIPTION
**Pull request by leewaa**
As part of https://github.com/theforeman/foreman/pull/5569

This adds the functionality to edit the network of an existing network and fixes some other issues with updating a vm. 

It also brings updating a vm into one request to the vsphere sdk reducing it from individual requests for each attribute.

#### TODO

- [x] Add tests
- [x] add mock implementation

### CODE REVIEW

**Comment by leewaa** [comment]
Thanks @timogoebel for the push in the right direction.

**Comment by leewaa** [comment]
Note: The tests here are basically useless.. @timogoebel and myself will be coming up with a better test strategy for the requests in the future so that we can bring up the stability and maintainability of this.

**Comment by timogoebel** [comment]
Thanks, @leewaa.

**Comment by timogoebel** [comment]
I just released v2.2.0 with these changes.

**Pull request merged**
