### PR TITLE
Add Gitter support and description

### PR DESCRIPTION
**Pull request by jrgarcia**
- Add Gitter badge
- Add description

### CODE REVIEW

**Comment by plribeiro3000** [comment]
@jrgarcia What are you trying to accomplish with gitter exactly?

**Comment by jrgarcia** [comment]
@plribeiro3000 I was taking a look at it to see about having a chat available for others that have been contributing to fog-vsphere. Though, as I look at it, I don't know that it will add that much. I think Issues works well enough. I might consider dropping Waffle too. What are your thoughts?

**Comment by plribeiro3000** [comment]
@jrgarcia What we are doing overall is to use issues for foreign people and slack for the core contributors. Do you have access to it?

**Comment by jrgarcia** [comment]
@plribeiro3000 Nope. By core contributor do you mean the Fog organization as a whole or the main fog/fog-core projects?

**Comment by plribeiro3000** [comment]
You are the main head in `fog-vsphere` so i you are part of the core team which are the main contributors. Since we are splitting projects to make development easier it makes a lot of sense to have more people being responsible for each small piece. =)

Whats your email so i can invite you?

**Comment by jrgarcia** [comment]
jr@garciaole.com

**Comment by plribeiro3000** [comment]
Just sent you an invite.

**Comment by jrgarcia** [comment]
:+1: Thanks!

**Pull request closed without merging**
