### PR TITLE
changing modify_vm_controller so that it follows the changes made to …

### PR DESCRIPTION
**Pull request by carlospuga**
…create_controller in 1.4.0

### CODE REVIEW

**Comment by plribeiro3000** [comment]
So this fixes a bug?

**Comment by jrgarcia** [comment]
@plribeiro3000 I'm not sure exactly what happened, I may have missed something. It appears that the lines before the `vm_reconfig_hardware` are all handled in the `create_controller` method that is called on the `controller` that's passed in.

**Comment by plribeiro3000** [comment]
@jrgarcia Thats fine. =)

I just wanted to make sure i was in the same page as @carlospuga.

**Comment by jrgarcia** [comment]
Understandable. I'm still digging in and making sure this won't change any behavior.

**Comment by plribeiro3000** [comment]
👍

**Pull request merged**
