### PR TITLE
Add disk and partitions info

### PR DESCRIPTION
**Pull request by sbernhard**

### CODE REVIEW

**Comment by chris1984** [comment]
@sbernhard i'll start to review this

**Comment by chris1984** [comment]
Looks like the tests are failing because of the PR. I will pull it down and work on a patch for you.

**Comment by sbernhard** [comment]
> Looks like the tests are failing because of the PR. I will pull it down and work on a patch for you.

You are right. I think the VCR cassettes needs to be updated. Unfortunately, I have no clue how.

**Comment by chris1984** [comment]
I think I figured out how to rerecord them, I am just going to merge this and will make a seperate pr to fix the tests then make a new release for you.

**Pull request merged**
