### PR TITLE
Add ability to create update and delete Resource Pools #253

### PR DESCRIPTION
**Pull request by rlazoryshchak**
- I've added posibility manage resource pools(create/update/delete).
 - I've faced with some problems with tests that is why I don't add any one :disappointed: but I promise to add when figure out these problems.

Create
```
compute.create_resource_pool(
  datacenter: 'datacenter_name', 
  cluster: 'cluster_name', 
  name: 'resource_pool_name', 
  cpu: {reservation: '2000'},
  memory: {reservation: '512'}
)
```
Update
```
compute.update_resource_pool(
  datacenter: 'datacenter_name', 
  cluster: 'cluster_name', 
  name: 'new_resource_pool_name', 
  cpu: {reservation: '3000'},
  memory: {reservation: '1024'},
  ref: 'resource_pool_id'
)
```
Delete
```
compute.destroy_resource_pool(
  datacenter: 'datacenter_name', 
  cluster: 'cluster_name', 
  ref: 'resource_pool_id'
)
```

### CODE REVIEW

**Comment by chris1984** [comment]
Starting to test

**Comment by ezr-ondrej** [comment]
Nice @rlazoryshchak! Do you want to follow up with the resources? These endpoints are used by the resources in `models/compute` for easier user access.

**Comment by rlazoryshchak** [comment]
@ezr-ondrej not sure. How I can do that?

**Comment by chris1984** [comment]
@rlazoryshchak im going to test this and if it looks good we can merge it, @ezr-ondrej was saying in a separate PR. I can help you with that when we get this one merged.

**Comment by rlazoryshchak** [comment]
@chris1984 okay

**Pull request merged**
