### PR TITLE
Add interim commits to fog/fog

### PR DESCRIPTION
**Pull request by jrgarcia**
Includes
- 14a4e94bbcd7c9d5c207199d076a555d2918be0b
- Use 1.8-style hash syntax for 1.8 compatability

### CODE REVIEW

**Comment by plribeiro3000** [comment]
Thats great @jrgarcia . One thing i did when extracting `fog-xenserver` was to ask the original reporter to submit it to the extracted gem as well. That did increased my free time to continue the extraction. =)

:+1:

**Comment by jrgarcia** [comment]
@plribeiro3000 Will do. I do have another question, what is the process for releasing a gem and deprecating the fog/fog vSphere provider?

**Comment by plribeiro3000** [comment]
To release we use `bundler` so all you will have to do is `rake release`.
After that you will need to add the 3 `fog` owners to the gem at rubygems, so they can release a new version if needed and then you will need top open a PR against `fog` removing all the code from there and adding support for `fog-vsphere`.

**Comment by jrgarcia** [comment]
@plribeiro3000 Okay, sounds good! Thanks!

**Comment by plribeiro3000** [comment]
Sure. You are welcome!

**Pull request merged**
