### PR TITLE
Create rule add cluster vm host rule info type

### PR DESCRIPTION
**Pull request by carlospuga**

### CODE REVIEW

**Comment by jrgarcia** [comment]
Can you give me a little background/context on this PR?

**Comment by carlospuga** [comment]
I'm looking for the ability to list and create drs rules of all types including 'ClusterVMHostRuleInfo' type.  Currently create_rule.rb and list_rule.rb only create and list Affinity and AntiAffinity rules.  This PR will allow the create_rule.rb and list_rule.rb to create and list the 'ClusterVMHostRuleInfo' rule type as well.

**Comment by pedantic-git** [comment]
Ah yes - that's my fault. The project I was on only needed the anti-affinity rules so that's all I implemented in the previously non-existent DRS classes.

**Comment by jrgarcia** [comment]
I'll try and get this merged in at some point today. Thanks for the PR!

**Comment by carlospuga** [comment]
Thank you both.

**Comment by jrgarcia** [comment]
Released v1.1.0 with this added.

**Pull request merged**
