### PR TITLE
clone_vm: change boot order

### PR DESCRIPTION
**Pull request by timogoebel**
This commit allows a developer to specify a new boot order for the cloned VM similar to when creating a new VM.

### CODE REVIEW

**Comment by chris1984** [comment]
Going to test this.

**Comment by timogoebel** [comment]
@jrgarcia: Would you mind taking a look at this? Test failures are unrelated.

**Comment by jrgarcia** [comment]
@timogoebel Yeah, I'm aware of the breakage in the tests. I haven't had time to fix it. Should be a simple fix, but I want to make sure it gets done correctly.

As for your code, it looks good, have you tested it in an actual environment?

**Comment by chris1984** [comment]
@jrgarcia let me start it right now, sorry for the delay

**Comment by jrgarcia** [comment]
@chris1984 It's not your job, no need to apologize. 😄 I was just curious.

**Comment by chris1984** [comment]
@jrgarcia happy to help :) I enjoy testing the pr's and helping VMware and Fog. I am trying to help out more and learn more Ruby. Testing looks good:

clone in foreman
http://nimb.ws/JVI4KC

vmware clone
http://nimb.ws/sMYA0k

Able to change boot order:
http://nimb.ws/qwXmvZ

**Comment by jrgarcia** [comment]
Thanks @chris1984! I tested it as well and it works fine for me too. Merging now...

**Comment by jrgarcia** [comment]
@timogoebel I'm going to be away from the computer for a while, but I'll put out a release as soon as I can.

**Comment by jrgarcia** [comment]
Released 1.13.0 with these and a few other changes. Thanks again for all of your contributions @timogoebel and thanks for helping with testing @chris1984!

**Comment by timogoebel** [comment]
@chris1984 & @jrgarcia: Thank you for your help with this.

**Pull request merged**
