### PR TITLE
Add NSX-T support in create_vm.rb

### PR DESCRIPTION
**Pull request by yasensim**
This allows connecting VMs to NSX-T Logical Switches. Please merge.

### CODE REVIEW

**Comment by timogoebel** [comment]
LGTM.

**Comment by nicholaspearson** [comment]
Thanks @yasensim 

Would appreciate if we could pull a support release too for fog-vsphere-0.6.0 with this code in. Unfortunately we are slightly version locked for the moment at 0.6.0.

Is this possible?

**Comment by yasensim** [comment]
Makes sense @dixonly I just changed it.
@nicholaspearson I will let the maintainers to advice s create_vm.rb is very different in v1.6.0. I can send separate PR.

**Comment by timogoebel** [comment]
If you could open a separate PR with the changes for 1.6.0 that‘d definitely help.
I‘m on pto this week and far away from a real computer, but will gladly create a release next week.

**Pull request merged**
