### PR TITLE
remove index argument to create_disk call

### PR DESCRIPTION
**Pull request by scambra**
It was removed in this commit 60a5dc320973ff6425bc941f24bae4e9187b57fa

### CODE REVIEW

**Comment by jrgarcia** [comment]
Thanks for catching this @scambra and thanks for your contribution! I'll try and release this fix this afternoon (CST).

**Comment by scambra** [comment]
Even with this fix, I can't add new volumes on clone yet, maybe I'm doing something wrong, or something else needs to be fixed

My code looks like this:
```ruby
server = <get server with id>
volumes = server.volumes.dup
volumes << server.volumes.new size: size_gb * 1048576
volumes.last.server = server
server.clone ...., volumes: volumes
```

And I get this error:
A RbVmomi::Fault occurred in cloud_vms#create:
  InvalidController: The device '3' is referring to a nonexisting controller '1,000'.


I added volumes.last.server = server line because I was getting this error:
A NoMethodError occurred in cloud_vms#create:
  undefined method `volumes' for nil:NilClass
  fog-vsphere (1.6.0) lib/fog/vsphere/models/compute/volume.rb:117:in `calculate_free_unit_number'

**Comment by jrgarcia** [comment]
Ok. I'm actually away today, but I'll try to get to a computer and take a look at this as soon as I can. Sorry you're running into problems with this!

**Comment by jrgarcia** [comment]
@scambra In the meantime, can you give me the versions of Ruby, fog-vsphere, fog, and rbvmomi? That will help me a lot.

**Comment by scambra** [comment]
ruby 2.3.1
fog-core 1.43.0
fog-vsphere 1.6.0
rbvmomi 1.9.4

**Pull request merged**
